<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PermaNotes.UI\PermaNotes.UI.csproj" />
    <ProjectReference Include="..\PermaNotes.Core\PermaNotes.Core.csproj" />
    <ProjectReference Include="..\PermaNotes.Platform.Windows\PermaNotes.Platform.Windows.csproj" />
    <ProjectReference Include="..\PermaNotes.Platform.MacOS\PermaNotes.Platform.MacOS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.2.8" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.8" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.8" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

</Project>
